<?php
/** Tour archive and filters. */
get_header();
$regions = get_terms( array( 'taxonomy' => 'wma_region', 'hide_empty' => false ) );
$styles = get_terms( array( 'taxonomy' => 'wma_style', 'hide_empty' => false ) );
$archive_title = is_tax() ? single_term_title( '', false ) : __( 'Journeys through Morocco', 'wild-morocco-adventures' );
$archive_intro = is_tax() ? term_description() : __( 'Use these journeys as inspiration. Every route can be reshaped around your pace, priorities and travel dates.', 'wild-morocco-adventures' );
?>
<header class="wma-page-hero wma-page-hero--tours" style="--page-image:url('<?php echo esc_url( wma_fallback_image( 'marrakech' ) ); ?>')"><div class="wma-container"><?php wma_breadcrumbs(); ?><span class="wma-eyebrow wma-eyebrow--light"><?php esc_html_e( 'Find your way into Morocco', 'wild-morocco-adventures' ); ?></span><h1><?php echo esc_html( $archive_title ); ?></h1><div class="wma-page-hero-copy"><?php echo wp_kses_post( $archive_intro ); ?></div></div></header>
<section class="wma-tour-browser"><div class="wma-container"><form class="wma-tour-filters" method="get" action="<?php echo esc_url( get_post_type_archive_link( 'wma_trip' ) ); ?>" data-wma-tour-filters data-wma-reveal>
	<div class="wma-filter-intro">
		<div><span class="wma-filter-kicker"><?php esc_html_e( 'Tailor your route', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'Find the journey that fits', 'wild-morocco-adventures' ); ?></h2></div>
		<p><span aria-hidden="true">✦</span><?php esc_html_e( 'Private & tailor-made', 'wild-morocco-adventures' ); ?></p>
	</div>
	<div class="wma-filter-control"><label for="wma-filter-region"><span aria-hidden="true">⌖</span><?php esc_html_e( 'Region', 'wild-morocco-adventures' ); ?></label><div class="wma-filter-select-wrap"><select id="wma-filter-region" name="region"><option value=""><?php esc_html_e( 'Everywhere', 'wild-morocco-adventures' ); ?></option><?php if ( ! is_wp_error( $regions ) ) { foreach ( $regions as $region ) { echo '<option value="' . esc_attr( $region->slug ) . '" ' . selected( sanitize_title( wp_unslash( $_GET['region'] ?? '' ) ), $region->slug, false ) . '>' . esc_html( $region->name ) . '</option>'; } } ?></select><i aria-hidden="true"></i></div></div>
	<div class="wma-filter-control"><label for="wma-filter-style"><span aria-hidden="true">✦</span><?php esc_html_e( 'Travel style', 'wild-morocco-adventures' ); ?></label><div class="wma-filter-select-wrap"><select id="wma-filter-style" name="style"><option value=""><?php esc_html_e( 'All styles', 'wild-morocco-adventures' ); ?></option><?php if ( ! is_wp_error( $styles ) ) { foreach ( $styles as $style ) { echo '<option value="' . esc_attr( $style->slug ) . '" ' . selected( sanitize_title( wp_unslash( $_GET['style'] ?? '' ) ), $style->slug, false ) . '>' . esc_html( $style->name ) . '</option>'; } } ?></select><i aria-hidden="true"></i></div></div>
	<div class="wma-filter-control"><label for="wma-filter-duration"><span aria-hidden="true">◷</span><?php esc_html_e( 'Maximum duration', 'wild-morocco-adventures' ); ?></label><div class="wma-filter-select-wrap"><select id="wma-filter-duration" name="duration_max"><option value=""><?php esc_html_e( 'Any length', 'wild-morocco-adventures' ); ?></option><?php foreach ( array( 5, 8, 12, 16 ) as $days ) { echo '<option value="' . esc_attr( (string) $days ) . '" ' . selected( absint( $_GET['duration_max'] ?? 0 ), $days, false ) . '>' . esc_html( sprintf( __( 'Up to %d days', 'wild-morocco-adventures' ), $days ) ) . '</option>'; } ?></select><i aria-hidden="true"></i></div></div>
	<div class="wma-filter-control"><label for="wma-filter-budget"><span aria-hidden="true">◎</span><?php esc_html_e( 'Budget per person', 'wild-morocco-adventures' ); ?></label><div class="wma-filter-select-wrap"><select id="wma-filter-budget" name="budget_max"><option value=""><?php esc_html_e( 'Any budget', 'wild-morocco-adventures' ); ?></option><?php foreach ( array( 750, 1000, 1500, 2500 ) as $budget ) { echo '<option value="' . esc_attr( (string) $budget ) . '" ' . selected( absint( $_GET['budget_max'] ?? 0 ), $budget, false ) . '>' . esc_html( sprintf( __( 'Up to €%d', 'wild-morocco-adventures' ), $budget ) ) . '</option>'; } ?></select><i aria-hidden="true"></i></div></div>
	<div class="wma-filter-control"><label for="wma-filter-sort"><span aria-hidden="true">↕</span><?php esc_html_e( 'Sort', 'wild-morocco-adventures' ); ?></label><div class="wma-filter-select-wrap"><select id="wma-filter-sort" name="sort"><option value=""><?php esc_html_e( 'Recommended', 'wild-morocco-adventures' ); ?></option><option value="duration" <?php selected( sanitize_key( wp_unslash( $_GET['sort'] ?? '' ) ), 'duration' ); ?>><?php esc_html_e( 'Shortest first', 'wild-morocco-adventures' ); ?></option><option value="price_asc" <?php selected( sanitize_key( wp_unslash( $_GET['sort'] ?? '' ) ), 'price_asc' ); ?>><?php esc_html_e( 'Price: low to high', 'wild-morocco-adventures' ); ?></option><option value="price_desc" <?php selected( sanitize_key( wp_unslash( $_GET['sort'] ?? '' ) ), 'price_desc' ); ?>><?php esc_html_e( 'Price: high to low', 'wild-morocco-adventures' ); ?></option></select><i aria-hidden="true"></i></div></div>
	<button class="wma-button wma-button--primary wma-filter-submit" type="submit"><span><?php esc_html_e( 'Show journeys', 'wild-morocco-adventures' ); ?></span><i aria-hidden="true">→</i></button>
</form>
<div class="wma-results-heading"><p><?php global $wp_query; echo esc_html( sprintf( _n( '%d journey', '%d journeys', $wp_query->found_posts, 'wild-morocco-adventures' ), $wp_query->found_posts ) ); ?></p><?php if ( array_filter( array( $_GET['region'] ?? '', $_GET['style'] ?? '', $_GET['duration_max'] ?? '', $_GET['budget_max'] ?? '', $_GET['sort'] ?? '' ) ) ) : ?><a href="<?php echo esc_url( get_post_type_archive_link( 'wma_trip' ) ); ?>"><?php esc_html_e( 'Clear filters', 'wild-morocco-adventures' ); ?></a><?php endif; ?></div>
<?php if ( have_posts() ) : ?><div class="wma-trip-grid"><?php while ( have_posts() ) { the_post(); get_template_part( 'template-parts/trip-card' ); } ?></div><?php the_posts_pagination( array( 'mid_size' => 1, 'prev_text' => __( 'Previous', 'wild-morocco-adventures' ), 'next_text' => __( 'Next', 'wild-morocco-adventures' ) ) ); ?><?php else : ?><div class="wma-empty-card"><h2><?php esc_html_e( 'No journeys match those filters yet.', 'wild-morocco-adventures' ); ?></h2><p><?php esc_html_e( 'Try widening your search, or tell us what you have in mind and we will shape a custom route.', 'wild-morocco-adventures' ); ?></p><a class="wma-button wma-button--primary" href="<?php echo esc_url( wma_quote_url() ); ?>"><?php esc_html_e( 'Plan a custom journey', 'wild-morocco-adventures' ); ?></a></div><?php endif; ?></div></section>
<?php get_footer(); ?>
