<?php
/** Site footer. */
defined( 'ABSPATH' ) || exit;
$business = function_exists( 'wma_get_setting' ) ? wma_get_setting( 'business_name', 'Wild Morocco Adventures' ) : 'Wild Morocco Adventures';
$phone = function_exists( 'wma_get_setting' ) ? wma_get_setting( 'phone' ) : '';
$email = function_exists( 'wma_get_setting' ) ? wma_get_setting( 'email' ) : '';
$address = function_exists( 'wma_get_setting' ) ? wma_get_setting( 'address' ) : '';
?></main>
<footer class="wma-site-footer"><div class="wma-footer-cta"><div class="wma-container wma-footer-cta-inner"><div><span class="wma-eyebrow wma-eyebrow--light"><?php esc_html_e( 'Your Morocco, thoughtfully made', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'A remarkable journey starts with a real conversation.', 'wild-morocco-adventures' ); ?></h2></div><a class="wma-button wma-button--light" href="<?php echo esc_url( wma_quote_url() ); ?>"><?php esc_html_e( 'Tell us your plans', 'wild-morocco-adventures' ); ?></a></div></div>
<div class="wma-container wma-footer-grid"><div class="wma-footer-brand"><a class="wma-wordmark wma-wordmark--footer" href="<?php echo esc_url( home_url( '/' ) ); ?>"><span class="wma-wordmark-mark" aria-hidden="true">W</span><span><strong><?php echo esc_html( $business ); ?></strong></span></a><p><?php esc_html_e( 'Private journeys shaped with local knowledge, generous hospitality and a deep respect for Morocco.', 'wild-morocco-adventures' ); ?></p><div class="wma-socials"><?php foreach ( array( 'instagram' => 'Instagram', 'facebook' => 'Facebook', 'youtube' => 'YouTube' ) as $key => $label ) { $url = function_exists( 'wma_get_setting' ) ? wma_get_setting( $key ) : ''; if ( $url ) { echo '<a href="' . esc_url( $url ) . '" target="_blank" rel="noopener noreferrer">' . esc_html( $label ) . '</a>'; } } ?></div></div>
<div><h2 class="wma-footer-heading"><?php esc_html_e( 'Explore', 'wild-morocco-adventures' ); ?></h2><?php wp_nav_menu( array( 'theme_location' => 'footer', 'container' => false, 'menu_class' => 'wma-footer-menu', 'fallback_cb' => false, 'depth' => 1 ) ); ?></div>
<div><h2 class="wma-footer-heading"><?php esc_html_e( 'Contact', 'wild-morocco-adventures' ); ?></h2><ul class="wma-footer-contact"><?php if ( $phone ) { echo '<li><a href="tel:' . esc_attr( preg_replace( '/[^0-9+]/', '', $phone ) ) . '">' . esc_html( $phone ) . '</a></li>'; } if ( $email ) { echo '<li><a href="mailto:' . esc_attr( antispambot( $email ) ) . '">' . esc_html( antispambot( $email ) ) . '</a></li>'; } if ( $address ) { echo '<li>' . nl2br( esc_html( $address ) ) . '</li>'; } if ( ! $phone && ! $email && ! $address ) { echo '<li><a href="' . esc_url( wma_quote_url() ) . '">' . esc_html__( 'Request a personalised quote', 'wild-morocco-adventures' ) . '</a></li>'; } ?></ul></div></div>
<div class="wma-container wma-footer-bottom"><p>&copy; <?php echo esc_html( wp_date( 'Y' ) ); ?> <?php echo esc_html( $business ); ?>.</p><?php wp_nav_menu( array( 'theme_location' => 'legal', 'container' => false, 'menu_class' => 'wma-legal-menu', 'fallback_cb' => false, 'depth' => 1 ) ); ?></div></footer>
<?php $whatsapp = function_exists( 'wma_get_setting' ) ? preg_replace( '/[^0-9]/', '', wma_get_setting( 'whatsapp' ) ) : ''; if ( $whatsapp ) : ?><a class="wma-whatsapp" href="https://wa.me/<?php echo esc_attr( $whatsapp ); ?>" target="_blank" rel="noopener noreferrer" aria-label="<?php esc_attr_e( 'Contact us on WhatsApp', 'wild-morocco-adventures' ); ?>"><span aria-hidden="true">WA</span></a><?php endif; ?>
<?php wp_footer(); ?></body></html>
