<?php
/** Individual tour. */
get_header(); the_post();
$id = get_the_ID(); $days = absint( wma_trip_meta( 'days' ) ); $nights = absint( wma_trip_meta( 'nights' ) ); $gallery_ids = array_filter( array_map( 'absint', explode( ',', (string) wma_trip_meta( 'gallery_ids' ) ) ) ); $main_image = has_post_thumbnail() ? get_the_post_thumbnail_url( $id, 'wma-hero' ) : wma_trip_fallback_image( $id );
$highlights = wma_trip_list( 'highlights' ); $itinerary = wma_trip_list( 'itinerary' ); $included = wma_trip_list( 'included' ); $excluded = wma_trip_list( 'excluded' ); $bring = wma_trip_list( 'what_to_bring' ); $faqs = wma_trip_list( 'faqs' );
$accommodation = (string) wma_trip_meta( 'accommodation' ); $advice = (string) wma_trip_meta( 'advice' ); $route_id = absint( wma_trip_meta( 'route_image_id' ) ); $subtitle = (string) wma_trip_meta( 'subtitle' );
?>
<article class="wma-trip-single"><header class="wma-trip-hero" style="--trip-image:url('<?php echo esc_url( (string) $main_image ); ?>')"><div class="wma-trip-hero-shade"></div><div class="wma-container wma-trip-hero-content"><?php wma_breadcrumbs(); ?><div class="wma-trip-hero-title"><div><span class="wma-eyebrow wma-eyebrow--light"><?php $styles = get_the_terms( $id, 'wma_style' ); echo esc_html( $styles && ! is_wp_error( $styles ) ? $styles[0]->name : __( 'Private Morocco journey', 'wild-morocco-adventures' ) ); ?></span><h1><?php the_title(); ?></h1><?php if ( $subtitle ) : ?><p><?php echo esc_html( $subtitle ); ?></p><?php endif; ?></div><aside class="wma-trip-summary"><span><?php esc_html_e( 'From', 'wild-morocco-adventures' ); ?></span><strong><?php echo esc_html( wma_trip_price() ); ?></strong><?php if ( $days ) : ?><p><?php echo esc_html( sprintf( __( '%1$d days / %2$d nights', 'wild-morocco-adventures' ), $days, $nights ) ); ?></p><?php endif; ?><a class="wma-button wma-button--primary" href="<?php echo esc_url( wma_quote_url( $id ) ); ?>"><?php esc_html_e( 'Request a quote', 'wild-morocco-adventures' ); ?></a></aside></div></div></header>

<nav class="wma-trip-nav" aria-label="<?php esc_attr_e( 'Tour sections', 'wild-morocco-adventures' ); ?>"><div class="wma-container"><a href="#overview"><?php esc_html_e( 'Overview', 'wild-morocco-adventures' ); ?></a><?php if ( $itinerary ) : ?><a href="#itinerary"><?php esc_html_e( 'Itinerary', 'wild-morocco-adventures' ); ?></a><?php endif; ?><?php if ( $accommodation ) : ?><a href="#accommodation"><?php esc_html_e( 'Accommodation', 'wild-morocco-adventures' ); ?></a><?php endif; ?><?php if ( $included || $excluded ) : ?><a href="#budget"><?php esc_html_e( 'Budget', 'wild-morocco-adventures' ); ?></a><?php endif; ?><?php if ( $advice ) : ?><a href="#advice"><?php esc_html_e( 'Advice', 'wild-morocco-adventures' ); ?></a><?php endif; ?><?php if ( $faqs ) : ?><a href="#trip-faq"><?php esc_html_e( 'FAQ', 'wild-morocco-adventures' ); ?></a><?php endif; ?></div></nav>

<section class="wma-section wma-trip-overview" id="overview"><div class="wma-container wma-trip-overview-grid"><div class="wma-rich-content"><span class="wma-eyebrow"><?php esc_html_e( 'The journey', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'A route with room to breathe', 'wild-morocco-adventures' ); ?></h2><?php the_content(); ?><?php if ( $highlights ) : ?><h3><?php esc_html_e( 'Moments to look forward to', 'wild-morocco-adventures' ); ?></h3><?php wma_item_list( $highlights ); ?><?php endif; ?></div><aside class="wma-trip-facts"><h2><?php esc_html_e( 'At a glance', 'wild-morocco-adventures' ); ?></h2><dl><?php foreach ( array( 'start_location' => __( 'Starts in', 'wild-morocco-adventures' ), 'end_location' => __( 'Ends in', 'wild-morocco-adventures' ), 'difficulty' => __( 'Activity level', 'wild-morocco-adventures' ), 'group_size' => __( 'Group style', 'wild-morocco-adventures' ) ) as $key => $label ) { $value = wma_trip_meta( $key ); if ( $value ) { echo '<div><dt>' . esc_html( $label ) . '</dt><dd>' . esc_html( (string) $value ) . '</dd></div>'; } } ?></dl><div class="wma-trip-taxonomies"><?php echo get_the_term_list( $id, 'wma_region', '', ' • ' ); ?></div></aside></div></section>

<?php if ( $gallery_ids ) : ?><section class="wma-section wma-section--sand"><div class="wma-container wma-gallery" data-wma-gallery><div class="wma-section-heading"><div><span class="wma-eyebrow"><?php esc_html_e( 'A glimpse ahead', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'Landscapes along the way', 'wild-morocco-adventures' ); ?></h2></div></div><?php $first = $gallery_ids[0]; ?><div class="wma-gallery-main"><img data-wma-gallery-main src="<?php echo esc_url( wp_get_attachment_image_url( $first, 'wma-gallery' ) ); ?>" alt="<?php echo esc_attr( get_post_meta( $first, '_wp_attachment_image_alt', true ) ); ?>"></div><div class="wma-gallery-thumbs"><?php foreach ( $gallery_ids as $index => $image_id ) : ?><button type="button" data-wma-gallery-thumb data-full="<?php echo esc_url( wp_get_attachment_image_url( $image_id, 'wma-gallery' ) ); ?>" aria-pressed="<?php echo 0 === $index ? 'true' : 'false'; ?>"><?php echo wp_get_attachment_image( $image_id, 'thumbnail', false, array( 'loading' => 'lazy' ) ); ?></button><?php endforeach; ?></div></div></section><?php endif; ?>

<?php if ( $itinerary ) : ?><section class="wma-section wma-itinerary-section" id="itinerary"><div class="wma-container wma-itinerary-layout"><div class="wma-itinerary-heading"><span class="wma-eyebrow"><?php esc_html_e( 'Day by day', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'Your journey in detail', 'wild-morocco-adventures' ); ?></h2><p><?php esc_html_e( 'This outline remains flexible until the final proposal is approved.', 'wild-morocco-adventures' ); ?></p><?php if ( $route_id ) : ?><img class="wma-route-image" src="<?php echo esc_url( wp_get_attachment_image_url( $route_id, 'large' ) ); ?>" alt="<?php echo esc_attr( get_post_meta( $route_id, '_wp_attachment_image_alt', true ) ); ?>" loading="lazy"><?php endif; ?></div><div class="wma-itinerary-list"><?php foreach ( $itinerary as $index => $day ) : if ( ! is_array( $day ) ) { continue; } ?><details <?php echo 0 === $index ? 'open' : ''; ?>><summary><span><?php echo esc_html( sprintf( __( 'Day %d', 'wild-morocco-adventures' ), absint( $day['day'] ?? $index + 1 ) ) ); ?></span><strong><?php echo esc_html( (string) ( $day['title'] ?? '' ) ); ?></strong><i aria-hidden="true">+</i></summary><div class="wma-itinerary-body"><?php if ( ! empty( $day['location'] ) ) : ?><p class="wma-itinerary-route"><?php echo esc_html( $day['location'] ); ?></p><?php endif; ?><?php echo wpautop( wp_kses_post( (string) ( $day['description'] ?? '' ) ) ); ?><?php if ( ! empty( $day['overnight'] ) ) : ?><p><strong><?php esc_html_e( 'Overnight:', 'wild-morocco-adventures' ); ?></strong> <?php echo esc_html( $day['overnight'] ); ?></p><?php endif; ?></div></details><?php endforeach; ?></div></div></section><?php endif; ?>

<?php if ( $accommodation ) : ?><section class="wma-section wma-section--olive wma-split-section" id="accommodation"><div class="wma-container wma-split-grid"><div><span class="wma-eyebrow wma-eyebrow--light"><?php esc_html_e( 'Where you will stay', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'Places with a sense of place', 'wild-morocco-adventures' ); ?></h2></div><div class="wma-rich-content wma-rich-content--light"><?php echo wpautop( wp_kses_post( $accommodation ) ); ?></div></div></section><?php endif; ?>

<?php if ( $included || $excluded ) : ?><section class="wma-section" id="budget"><div class="wma-container"><div class="wma-section-heading"><div><span class="wma-eyebrow"><?php esc_html_e( 'Clear from the start', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'Budget and services', 'wild-morocco-adventures' ); ?></h2></div><p><?php esc_html_e( 'The final price depends on dates, availability, traveller numbers and the services selected. Your proposal will confirm every detail.', 'wild-morocco-adventures' ); ?></p></div><div class="wma-inclusion-grid"><?php if ( $included ) : ?><div><h3><?php esc_html_e( 'Included', 'wild-morocco-adventures' ); ?></h3><?php wma_item_list( $included ); ?></div><?php endif; ?><?php if ( $excluded ) : ?><div><h3><?php esc_html_e( 'Not included', 'wild-morocco-adventures' ); ?></h3><?php wma_item_list( $excluded, 'wma-cross-list' ); ?></div><?php endif; ?></div></div></section><?php endif; ?>

<?php if ( $advice || $bring ) : ?><section class="wma-section wma-section--sand" id="advice"><div class="wma-container wma-advice-grid"><div class="wma-rich-content"><span class="wma-eyebrow"><?php esc_html_e( 'Good to know', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'Practical advice', 'wild-morocco-adventures' ); ?></h2><?php echo wpautop( wp_kses_post( $advice ) ); ?></div><?php if ( $bring ) : ?><aside><h3><?php esc_html_e( 'What to bring', 'wild-morocco-adventures' ); ?></h3><?php wma_item_list( $bring ); ?></aside><?php endif; ?></div></section><?php endif; ?>

<?php if ( $faqs ) : ?><section class="wma-section wma-faq-section" id="trip-faq"><div class="wma-container wma-faq-layout"><div><span class="wma-eyebrow"><?php esc_html_e( 'Before you go', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'Questions, answered', 'wild-morocco-adventures' ); ?></h2></div><div class="wma-faq-list"><?php foreach ( $faqs as $faq ) : if ( ! is_array( $faq ) ) { continue; } ?><details><summary><?php echo esc_html( (string) ( $faq['question'] ?? '' ) ); ?><i aria-hidden="true">+</i></summary><div><?php echo wpautop( wp_kses_post( (string) ( $faq['answer'] ?? '' ) ) ); ?></div></details><?php endforeach; ?></div></div></section><?php endif; ?>

<?php $trip_testimonials = new WP_Query( array( 'post_type' => 'wma_testimonial', 'post_status' => 'publish', 'posts_per_page' => 3, 'orderby' => 'menu_order date', 'order' => 'DESC' ) ); if ( $trip_testimonials->have_posts() ) : ?><section class="wma-section wma-section--testimonials"><div class="wma-container"><span class="wma-eyebrow"><?php esc_html_e( 'Traveller stories', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'Words carried home', 'wild-morocco-adventures' ); ?></h2><div class="wma-testimonial-grid"><?php while ( $trip_testimonials->have_posts() ) : $trip_testimonials->the_post(); ?><blockquote><div class="wma-stars" aria-label="<?php echo esc_attr( sprintf( __( '%d out of 5 stars', 'wild-morocco-adventures' ), absint( get_post_meta( get_the_ID(), '_wma_rating', true ) ) ) ); ?>"><?php echo esc_html( str_repeat( '★', absint( get_post_meta( get_the_ID(), '_wma_rating', true ) ) ) ); ?></div><?php the_content(); ?><footer><strong><?php the_title(); ?></strong><span><?php echo esc_html( (string) get_post_meta( get_the_ID(), '_wma_location', true ) ); ?></span></footer></blockquote><?php endwhile; wp_reset_postdata(); ?></div></div></section><?php endif; ?>

<section class="wma-section wma-trip-quote" style="--quote-image:url('<?php echo esc_url( wma_fallback_image( 'marrakech' ) ); ?>')"><div class="wma-container"><div class="wma-trip-quote-copy"><span class="wma-eyebrow wma-eyebrow--light"><?php esc_html_e( 'Make it yours', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'Ready to shape this journey around you?', 'wild-morocco-adventures' ); ?></h2><p><?php esc_html_e( 'Share your dates, pace and interests. We will turn this inspiration into a personal proposal.', 'wild-morocco-adventures' ); ?></p><a class="wma-button wma-button--primary" href="<?php echo esc_url( wma_quote_url( $id ) ); ?>"><?php esc_html_e( 'Request my quote', 'wild-morocco-adventures' ); ?></a></div></div></section>

<?php $related_ids = wma_trip_list( 'related_trip_ids' ); $related_args = array( 'post_type' => 'wma_trip', 'post_status' => 'publish', 'posts_per_page' => 3, 'post__not_in' => array( $id ) ); if ( $related_ids ) { $related_args['post__in'] = array_map( 'absint', $related_ids ); $related_args['orderby'] = 'post__in'; } $related = new WP_Query( $related_args ); if ( $related->have_posts() ) : ?><section class="wma-section"><div class="wma-container"><div class="wma-section-heading"><div><span class="wma-eyebrow"><?php esc_html_e( 'Keep exploring', 'wild-morocco-adventures' ); ?></span><h2><?php esc_html_e( 'Other journeys you may love', 'wild-morocco-adventures' ); ?></h2></div></div><div class="wma-trip-grid"><?php while ( $related->have_posts() ) { $related->the_post(); get_template_part( 'template-parts/trip-card' ); } wp_reset_postdata(); ?></div></div></section><?php endif; ?>
</article><a class="wma-mobile-quote" href="<?php echo esc_url( wma_quote_url( $id ) ); ?>"><?php esc_html_e( 'Request a quote', 'wild-morocco-adventures' ); ?></a>
<?php get_footer(); ?>
